In [2]:
import matplotlib.pyplot as plt
import xarray as xr
import numpy as np
import os
import sys

In [259]:
g=xr.open_dataset(os.path.join(os.environ.get('rawdir'),'trunk','test_grd.nc'))
b=xr.open_dataset(os.path.join(os.environ.get('rawdir'),'trunk','waom10_grd.nc'))

In [260]:
for key,value in g.items():
    if key not in n:
        g = g.drop(key)

/home/ubuntu/bigStick/anaconda3/envs/tidal_melting/lib/python3.6/_collections_abc.py:743: FutureWarning: iteration over an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Iterate over the Dataset.variables property instead to preserve existing behavior in a forwards compatible manner.
  for key in self._mapping:


In [261]:
g

<xarray.Dataset>
Dimensions:    (eta_psi: 71, eta_rho: 72, eta_u: 72, eta_v: 71, one: 1, xi_psi: 76, xi_rho: 77, xi_u: 76, xi_v: 77)
Dimensions without coordinates: eta_psi, eta_rho, eta_u, eta_v, one, xi_psi, xi_rho, xi_u, xi_v
Data variables:
    spherical  |S1 ...
    xl         (one) float64 ...
    el         (one) float64 ...
    h          (eta_rho, xi_rho) float64 ...
    f          (eta_rho, xi_rho) float64 ...
    pm         (eta_rho, xi_rho) float64 ...
    pn         (eta_rho, xi_rho) float64 ...
    dndx       (eta_rho, xi_rho) float64 ...
    dmde       (eta_rho, xi_rho) float64 ...
    lat_rho    (eta_rho, xi_rho) float64 ...
    lon_rho    (eta_rho, xi_rho) float64 ...
    lat_psi    (eta_psi, xi_psi) float64 ...
    lon_psi    (eta_psi, xi_psi) float64 ...
    lat_u      (eta_u, xi_u) float64 ...
    lon_u      (eta_u, xi_u) float64 ...
    lat_v      (eta_v, xi_v) float64 ...
    lon_v      (eta_v, xi_v) float64 ...
    mask_rho   (eta_rho, xi_rho) float64 ...
    mas

In [277]:
g['spherical']=n.spherical
g

<xarray.Dataset>
Dimensions:    (eta_psi: 71, eta_rho: 72, eta_u: 72, eta_v: 71, one: 1, xi_psi: 76, xi_rho: 77, xi_u: 76, xi_v: 77)
Dimensions without coordinates: eta_psi, eta_rho, eta_u, eta_v, one, xi_psi, xi_rho, xi_u, xi_v
Data variables:
    xl         (one) float64 ...
    el         (one) float64 ...
    h          (eta_rho, xi_rho) float64 ...
    f          (eta_rho, xi_rho) float64 ...
    pm         (eta_rho, xi_rho) float64 ...
    pn         (eta_rho, xi_rho) float64 ...
    dndx       (eta_rho, xi_rho) float64 ...
    dmde       (eta_rho, xi_rho) float64 ...
    lat_rho    (eta_rho, xi_rho) float64 ...
    lon_rho    (eta_rho, xi_rho) float64 ...
    lat_psi    (eta_psi, xi_psi) float64 ...
    lon_psi    (eta_psi, xi_psi) float64 ...
    lat_u      (eta_u, xi_u) float64 ...
    lon_u      (eta_u, xi_u) float64 ...
    lat_v      (eta_v, xi_v) float64 ...
    lon_v      (eta_v, xi_v) float64 ...
    mask_rho   (eta_rho, xi_rho) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.

In [266]:
n

<xarray.Dataset>
Dimensions:    (eta_psi: 529, eta_rho: 530, eta_u: 530, eta_v: 529, one: 1, xi_psi: 629, xi_rho: 630, xi_u: 629, xi_v: 630)
Dimensions without coordinates: eta_psi, eta_rho, eta_u, eta_v, one, xi_psi, xi_rho, xi_u, xi_v
Data variables:
    h          (eta_rho, xi_rho) float64 3.532e+03 3.615e+03 2.78e+03 ...
    spherical  |S1 b'1'
    angle      (eta_rho, xi_rho) float64 -2.304 -2.305 -2.307 -2.309 -2.31 ...
    pm         (eta_rho, xi_rho) float64 0.0001077 0.0001077 0.0001076 ...
    pn         (eta_rho, xi_rho) float64 0.0001077 0.0001077 0.0001076 ...
    dndx       (eta_rho, xi_rho) float64 -3.747e-08 -3.734e-08 -3.722e-08 ...
    dmde       (eta_rho, xi_rho) float64 -3.372e-08 -3.372e-08 -3.372e-08 ...
    f          (eta_rho, xi_rho) float64 -0.0001181 -0.0001182 -0.0001183 ...
    lon_rho    (eta_rho, xi_rho) float64 -132.0 -132.1 -132.2 -132.3 -132.4 ...
    lat_rho    (eta_rho, xi_rho) float64 -54.09 -54.16 -54.22 -54.28 -54.34 ...
    lon_psi    (eta_psi, x

In [276]:
for key,val in b.items():
    if key not in ['xl',"el",'hraw',"zice"]:
        n[key] = (g[key].dims,np.array(b[key].values,dtype=g[key].dtype))
        n[key].attrs = g[key].attrs

/home/ubuntu/bigStick/anaconda3/envs/tidal_melting/lib/python3.6/_collections_abc.py:743: FutureWarning: iteration over an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Iterate over the Dataset.variables property instead to preserve existing behavior in a forwards compatible manner.
  for key in self._mapping:


In [279]:
g['xl']=n.xl
g['el']=n.el

In [292]:
keys=[]
for key,val in g.items():
    if val.dims == ('eta_psi','xi_psi'):
        print(key)
        g= g.drop(key)
        keys.append(key)

lat_psi
lon_psi
mask_psi


/home/ubuntu/bigStick/anaconda3/envs/tidal_melting/lib/python3.6/_collections_abc.py:743: FutureWarning: iteration over an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Iterate over the Dataset.variables property instead to preserve existing behavior in a forwards compatible manner.
  for key in self._mapping:


In [293]:
for key in keys:
    g[key]=n[key]

In [294]:
g

<xarray.Dataset>
Dimensions:    (eta_psi: 529, eta_rho: 530, eta_u: 530, eta_v: 529, one: 1, xi_psi: 629, xi_rho: 630, xi_u: 629, xi_v: 630)
Dimensions without coordinates: eta_psi, eta_rho, eta_u, eta_v, one, xi_psi, xi_rho, xi_u, xi_v
Data variables:
    xl         (one) float64 6.3e+06
    el         (one) float64 6.3e+06
    spherical  |S1 b'1'
    f          (eta_rho, xi_rho) float64 -0.0001181 -0.0001182 -0.0001183 ...
    pm         (eta_rho, xi_rho) float64 0.0001077 0.0001077 0.0001076 ...
    pn         (eta_rho, xi_rho) float64 0.0001077 0.0001077 0.0001076 ...
    dndx       (eta_rho, xi_rho) float64 -3.747e-08 -3.734e-08 -3.722e-08 ...
    dmde       (eta_rho, xi_rho) float64 -3.372e-08 -3.372e-08 -3.372e-08 ...
    lat_rho    (eta_rho, xi_rho) float64 -54.09 -54.16 -54.22 -54.28 -54.34 ...
    lon_rho    (eta_rho, xi_rho) float64 -132.0 -132.1 -132.2 -132.3 -132.4 ...
    mask_rho   (eta_rho, xi_rho) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 ...
    angle      (eta_rho,

In [257]:
key = 'el'
n[key] = ((g[key].dims[0]),np.array([b.xl.values],dtype=g[key].dtype))
n[key].attrs = g[key].attrs
n.xl

<xarray.DataArray 'xl' (one: 1)>
array([6300000.])
Dimensions without coordinates: one
Attributes:
    long_name:  domain length in the XI-direction
    units:      meter

In [295]:
out_path=os.path.join('~/raijin/short/m68/oxr581/trunk','test_grd.nc3')
g.to_netcdf(out_path,'w',unlimited_dims='bath')

In [273]:
g = g.drop('spherical')

In [163]:
for key in ['rho','u','v','psi']:
    x,y = np.meshgrid(b['xi_'+key]*10000,b['eta_'+key]*10000)
    b["x_"+key] = (('eta_'+key,'xi_'+key),x)
    b['x_'+key].attrs = g['x_'+key].attrs
    b["y_"+key] = (('eta_'+key,'xi_'+key),y)
    b['y_'+key].attrs = g['y_'+key].attrs

<xarray.DataArray 'y_psi' (eta_psi: 529, xi_psi: 629)>
array([[      0,       0,       0, ...,       0,       0,       0],
       [  10000,   10000,   10000, ...,   10000,   10000,   10000],
       [  20000,   20000,   20000, ...,   20000,   20000,   20000],
       ...,
       [5260000, 5260000, 5260000, ..., 5260000, 5260000, 5260000],
       [5270000, 5270000, 5270000, ..., 5270000, 5270000, 5270000],
       [5280000, 5280000, 5280000, ..., 5280000, 5280000, 5280000]])
Dimensions without coordinates: eta_psi, xi_psi
Attributes:
    long_name:  y location of PSI-points
    units:      meter

In [161]:
g.x_u

<xarray.DataArray 'x_u' (eta_u: 72, xi_u: 76)>
array([[    0.,   200.,   400., ..., 14600., 14800., 15000.],
       [    0.,   200.,   400., ..., 14600., 14800., 15000.],
       [    0.,   200.,   400., ..., 14600., 14800., 15000.],
       ...,
       [    0.,   200.,   400., ..., 14600., 14800., 15000.],
       [    0.,   200.,   400., ..., 14600., 14800., 15000.],
       [    0.,   200.,   400., ..., 14600., 14800., 15000.]])
Dimensions without coordinates: eta_u, xi_u
Attributes:
    long_name:  x location of U-points
    units:      meter

In [142]:
for key,value in g.items():
    if key not in b:
        print(key)
        b[key]=((value.dims

JPRJ
PLAT
PLONG
ROTA
JLTS
P1
P2
P3
P4
XOFF
YOFF
depthmin
depthmax
x_rho
y_rho
x_psi
y_psi
x_u
y_u
x_v
y_v


/home/ubuntu/bigStick/anaconda3/envs/tidal_melting/lib/python3.6/_collections_abc.py:743: FutureWarning: iteration over an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Iterate over the Dataset.variables property instead to preserve existing behavior in a forwards compatible manner.
  for key in self._mapping:
